import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import { ConvexHttpClient } from "convex/browser";
import { api } from "../convex/_generated/api";
import "@fontsource/nunito-sans/latin-400.css";
import "@fontsource/nunito-sans/latin-600.css";
import "@fontsource/nunito-sans/latin-800.css";
import "./style.css";
import { task, initialState, generated, judged, assessed, correction, saveResult, loadState } from "./practice.mjs";

const KEY="prompt-game:beginner-01:v1";
const TOKEN="prompt-game:session:v1";
const client=__CONVEX_URL__?new ConvexHttpClient(__CONVEX_URL__):null;
function sessionToken(){let token=localStorage.getItem(TOKEN);if(!token){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,"0")).join("");localStorage.setItem(TOKEN,token);}return token;}
function message(error){const text=String(error?.message||error);if(text.includes("AI_UNAVAILABLE"))return "Answers and feedback are unavailable right now. Your work is still here.";if(text.includes("DAILY_ALLOWANCE"))return "Today's AI allowance has been reached. Keep your work and return after midnight UTC.";if(text.includes("REQUEST_PENDING"))return "This request is still processing. Wait a moment, then retry.";if(text.includes("PRACTICE_FINISHED"))return "This practice has already been assessed. Keep your confirmed result.";return "This request could not be completed. Your work is still here. Try again.";}
function Progress({state,pending}){const point=state.point&&!pending;return <nav className="progress" aria-label="Learning progress"><div className="level current"><span className="level-symbol" aria-hidden="true">1</span><div><strong>Beginner</strong><span>{pending?"Save pending":point?"Practice 1 ? Point earned":state.stage==="example"?"Practice 1 ? Completed with help":"Practice 1 of 2 ? Current"}</span></div></div><div className="level locked"><span className="level-symbol" aria-hidden="true">2</span><div><strong>Amateur</strong><span>Locked ? Pass Beginner's final</span></div></div><div className="level locked"><span className="level-symbol" aria-hidden="true">3</span><div><strong>Pro</strong><span>Locked ? Pass Amateur's final</span></div></div><div className="points"><strong>{point?1:0}<span> / 6</span></strong><span>Skill points</span></div></nav>;}
function Requirements({open=false}){return <details className="requirements" open={open||undefined}><summary>Task requirements</summary><ul>{task.requirements.map(r=><li key={r}>{r}</li>)}</ul></details>;}
function Answers({state}){
  const [tab,setTab]=useState("new");const positions=useRef({});const body=useRef(null);
  useEffect(()=>{setTab("new");if(body.current)body.current.scrollTop=0;},[state.answer?.id]);
  const old=state.previousAnswer?.text||task.original;
  function switchTab(next){if(body.current)positions.current[tab]=body.current.scrollTop;setTab(next);requestAnimationFrame(()=>{if(body.current)body.current.scrollTop=positions.current[next]||0;});}
  return <section aria-label="Answer comparison" className="answer-section" id="answer-view"><div className="comparison-tools"><div className="answer-tabs" role="tablist" aria-label="Compare answers"><button type="button" role="tab" aria-selected={tab==="old"} onClick={()=>switchTab("old")} aria-controls="phone-answer" id="tab-old">{state.previousAnswer?"Previous answer":"Original answer"}</button><button type="button" role="tab" aria-selected={tab==="new"} onClick={()=>switchTab("new")} aria-controls="phone-answer" id="tab-new">{state.previousAnswer?"Revised answer":"Your answer"}</button></div><a href="#judgment" onClick={()=>requestAnimationFrame(()=>document.getElementById("judgment")?.focus())}>Write my judgment</a></div><div className="answer-grid"><article className="desktop-answer"><h3>{state.previousAnswer?"Previous answer":"Original example"}</h3><p>{old}</p></article><article className="desktop-answer"><h3>{state.previousAnswer?"Revised answer":"Your answer"}</h3><p>{state.answer.text}</p></article></div><article className="phone-answer" id="phone-answer" role="tabpanel" aria-labelledby={tab==="old"?"tab-old":"tab-new"} ref={body}><h3>{tab==="old"?(state.previousAnswer?"Previous answer":"Original example"):(state.previousAnswer?"Revised answer":"Your answer")}</h3><p>{tab==="old"?old:state.answer.text}</p></article></section>;
}
function App(){
  const [s,setS]=useState(()=>loadState(()=>localStorage.getItem(KEY)));
  const [pending,setPending]=useState(null);const [saveError,setSaveError]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState("");const request=useRef(null);const announcement=useRef(null);
  useEffect(()=>{try{if(!localStorage.getItem(KEY))persist(s);}catch{setSaveError(true);}},[]);
  useEffect(()=>{if(["feedback","complete","example"].includes(s.stage))announcement.current?.focus();},[s.stage]);
  function persist(next,{confirmed=false}={}){const result=saveResult(next,value=>localStorage.setItem(KEY,value));setS(next);setSaveError(!result.saved);if(confirmed)setPending(result.pending);return result.saved;}
  function edit(field,value){setError("");request.current=null;persist({...s,[field]:value});}
  async function generate(){
    if(!s.prompt.trim()){setError("Add a prompt before generating an answer.");return;}if(s.correcting&&!s.explanation.trim()){setError("Explain what you changed and why before generating.");return;}
    if(!client){setError("Answers are unavailable right now. Your edit is still here.");return;}
    setBusy("Generating your answer");setError("");
    try {const token=sessionToken();const payload={token,prompt:s.prompt};const fingerprint=JSON.stringify(payload);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};const answer=await client.action(api.practice.generate,{...payload,requestId:request.current.id});persist(generated(s,answer),{confirmed:true});request.current=null;}
    catch(e){setError(message(e));}finally{setBusy("");}
  }
  async function assess(){
    if(!s.judgment.trim()){setError("Explain whether this answer meets the task before submitting.");return;}if(s.correcting&&!s.explanation.trim()){setError("Explain your correction before submitting.");return;}if(!client){setError("Feedback is unavailable right now. Your judgment is still here.");return;}
    setBusy("Checking your correction");setError("");
    try {const payload={token:sessionToken(),answerId:s.answer.id,judgment:s.judgment,explanation:s.explanation,...(s.correcting?{previousAssessmentId:s.feedback.id}:{})};const fingerprint=JSON.stringify(payload);if(request.current?.fingerprint!==fingerprint)request.current={fingerprint,id:crypto.randomUUID()};const f=await client.action(api.practice.assess,{...payload,requestId:request.current.id});persist(assessed(s,f),{confirmed:true});request.current=null;}
    catch(e){setError(message(e));}finally{setBusy("");}
  }
  const isEdit=s.stage==="edit"||s.stage==="editCorrection";
  const isJudge=s.stage==="judge"||s.stage==="judgeCorrection";
  const hasFeedback=!!s.feedback;
  return <><header className="site-header"><a href="/" className="wordmark">Prompting Game<span className="brand-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 5h16v11H10l-5 4v-4H4z"/><path d="m9 10 2 2 4-4"/></svg></span></a><span className="device-save">{saveError?"Device save failed":"Progress on this device"}</span></header><main><Progress state={s} pending={pending}/><div className="workspace"><div className="intro"><h1>Get answers that fit what you need.</h1><p>Practise improving a prompt, compare AI answers, and learn what to trust.</p></div><div className="challenge-heading"><div><span className="practice-label">Beginner practice 1 of 2</span><h2>{task.title}</h2></div><span className="attempts">{s.attempts} of 3 attempts used</span></div><p className="task-brief">{task.brief}</p><Requirements open={isEdit}/>
    {saveError&&!pending&&<div className="error" role="alert">This edit could not be saved on this device. Keep this page open and copy your work before leaving.</div>}
    {pending&&<section className="error" role="alert"><h3>Result checked ? save pending</h3><p>Your work is still on this page. Retry saving the same result; your answer will not be assessed again.</p><button className="primary" onClick={()=>persist(pending,{confirmed:true})}>Retry saving</button></section>}
    {error&&<p className="error" role="alert">{error}</p>}
    {busy&&<p className="busy" role="status">{busy}? Your work remains visible.</p>}
    {hasFeedback&&s.stage!=="complete"&&s.stage!=="example"&&<section className="feedback" tabIndex={-1} ref={announcement}><h3>{s.stage==="feedback"?"One change to try":"Your feedback"}</h3><p><strong>Gap:</strong> {s.feedback.gap}</p><p><strong>Why it matters:</strong> {s.feedback.why}</p><p className="evidence">{s.feedback.evidence}</p></section>}
    {isEdit&&<section className="editor"><label htmlFor="prompt">{s.correcting?"Edit your prompt":"Edit this prompt"}</label><p id="prompt-help">Change it to meet the task before generating.</p><textarea id="prompt" rows={6} maxLength={6000} value={s.prompt} aria-describedby="prompt-help" onChange={e=>edit("prompt",e.target.value)} disabled={!!busy||!!pending}/>{s.correcting&&<><label htmlFor="explanation">What did you change, and why?</label><textarea id="explanation" rows={3} maxLength={6000} value={s.explanation} onChange={e=>edit("explanation",e.target.value)} disabled={!!busy||!!pending}/><details className="previous-context"><summary>Review the previous answer</summary><p>{s.answer?.text}</p></details></>}<button className="primary" onClick={generate} disabled={!!busy||!!pending}>{s.correcting?"Generate revised answer":"Generate answer"}</button>{!s.correcting&&<details className="original"><summary>Original example answer</summary><p>{task.original}</p><span>This is a prepared example, not a new AI answer.</span></details>}</section>}
    {isJudge&&<><Answers state={s}/><section className="judgment"><details className="submitted"><summary>Submitted prompt</summary><p>{s.prompt}</p></details><label htmlFor="judgment">{s.correcting&&s.previousAnswer?"Does this revised answer meet the task? Explain why.":"Does your answer meet the task? Explain why."}</label><textarea id="judgment" rows={4} maxLength={6000} value={s.judgment} onChange={e=>edit("judgment",e.target.value)} disabled={!!busy||!!pending}/><a href="#answer-view">Back to answer</a>{s.correcting&&!s.previousAnswer&&<><label htmlFor="explanation">What did you change in your judgment, and why?</label><textarea id="explanation" rows={3} maxLength={6000} value={s.explanation} onChange={e=>edit("explanation",e.target.value)} disabled={!!busy||!!pending}/></>}{s.correcting&&s.previousAnswer&&<p className="evidence"><strong>Your explanation:</strong> {s.explanation}</p>}<button className="primary" onClick={assess} disabled={!!busy||!!pending}>{s.correcting?(s.previousAnswer?"Check my correction":"Check my corrected judgment"):"Check my judgment"}</button></section></>}
    {s.stage==="feedback"&&!pending&&<button className="primary" disabled={!!busy} onClick={()=>{request.current=null;persist(correction(s));}}>Try again</button>}
    {s.stage==="complete"&&<section className="result" tabIndex={-1} ref={announcement}><div className="reward" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M24 4 41 14v20L24 44 7 34V14Z"/><path d="m15 24 6 6 13-13"/></svg></div><h2>{pending?"Result checked ? save pending":"Skill point earned"}</h2><p>{s.feedback.why}</p><p className="evidence">{s.feedback.evidence}</p><p className="completion-note">First practice complete. More challenges will follow.</p></section>}
    {s.stage==="example"&&<section className="result" tabIndex={-1} ref={announcement}><h2>Completed with help</h2><p>You used your two retries. Compare your work with this example.</p><h3>One useful prompt</h3><p>{task.examplePrompt}</p><h3>Example answer</h3><p>{task.exampleAnswer}</p><p>It specifies the audience, facts and limits. You still need to check the answer; a good prompt cannot guarantee a good result.</p><p className="completion-note">No independent skill point earned. This does not prevent taking a fresh final later.</p></section>}
    <footer className="save-note"><p>{saveError?"Account backup is not connected. Keep this page open if device saving failed.":"Saved on this device only. Account backup is not available yet."}</p><p>Points reward independent practice. Badges mark final passes.</p></footer></div></main></>;
}

createRoot(document.getElementById("root")).render(<App/>);
