import React, { useEffect, useRef, useState } from "react";
import BaseAnswer from "./Answer.jsx";
import { studentFeedback } from "./feedbackText.mjs";
import { practiceFinished, isReview } from "./practice.mjs";
import "./practiceFlow.css";

const names=["Task","Weak prompt","Edit","AI answer","Your judgment","Feedback"];
const Answer=props=><BaseAnswer {...props} practiceMath/>;
const viewKey=id=>`prompt-game:${id}:view:v1`;
function allowed(state){
  if(state.stage==="edit")return state.answer?[3]:[1,2,3];
  if(state.stage==="editCorrection")return [3];
  if(state.stage==="judgeCorrection"&&!state.previousAnswer)return [5,4];
  if(state.stage==="judge"||state.stage==="judgeCorrection")return [4,5];
  return [6];
}
function initialView(id,state,preview,errorAction){
  const choices=allowed(state);
  if(errorAction==="assess")return 5;
  if(!preview)try{const stored=JSON.parse(localStorage.getItem(viewKey(id)));if(stored?.stage===state.stage&&stored?.answerId===state.answer?.id&&choices.includes(stored.step))return stored.step;}catch{}
  return choices[0];
}
function Requirements({task,open=false}){return <details className="requirements" open={open||undefined}><summary>Task requirements</summary><ul>{task.requirements.map(r=><li key={r}>{r}</li>)}</ul></details>;}

export default function PracticeFlow({state:s,task,challengeId,records,pending,saveError,error,errorAction,busy,allowanceReached,preview,edit,editPrompt,generate,assess,challenge,retrySaving,tryAgain,openPractice,startFinal,variantsExhausted,successSummary,notice,learningCue,Progress}){
  const review=isReview(challengeId);
  const feedback=studentFeedback(s.feedback);
  const [view,setView]=useState(()=>({stage:s.stage,answerId:s.answer?.id,step:initialView(challengeId,s,preview,errorAction)}));
  const [tab,setTab]=useState("new");
  const [celebrate,setCelebrate]=useState(false);
  const previousStage=useRef(s.stage),previousPoint=useRef(Boolean(s.point&&!pending));
  const heading=useRef(null),answerBody=useRef(null),positions=useRef({});
  const locked=!!busy||!!pending||saveError||!!errorAction;
  const choices=allowed(s);
  const current=view.stage===s.stage&&view.answerId===s.answer?.id&&choices.includes(view.step)?view.step:choices[0];
  useEffect(()=>{
    if(previousStage.current!==s.stage){setTab("new");positions.current={};previousStage.current=s.stage;}
    const confirmed=Boolean(s.point&&!pending);
    if(confirmed&&!previousPoint.current&&!preview){setCelebrate(true);}
    previousPoint.current=confirmed;
  },[s.stage,s.answer?.id,s.point,pending]);
  useEffect(()=>{if(!celebrate)return;const timer=setTimeout(()=>setCelebrate(false),800);return()=>clearTimeout(timer);},[celebrate]);
  useEffect(()=>{if(!preview)try{localStorage.setItem(viewKey(challengeId),JSON.stringify({step:current,stage:s.stage,answerId:s.answer?.id}));}catch{}heading.current?.focus();},[current,s.stage,s.answer?.id]);
  function go(next){if(busy||pending)return;if(answerBody.current)positions.current[tab]=answerBody.current.scrollTop;setView({stage:s.stage,answerId:s.answer?.id,step:next});}
  function compare(next){if(answerBody.current)positions.current[tab]=answerBody.current.scrollTop;setTab(next);requestAnimationFrame(()=>{if(answerBody.current)answerBody.current.scrollTop=positions.current[next]||0;});}
  useEffect(()=>{if(answerBody.current)answerBody.current.scrollTop=positions.current[tab]||0;},[current]);
  const old=s.previousAnswer?.text||task.original;
  const pointCount=Object.entries({...records,[challengeId]:s}).reduce((total,[id,value])=>total+(["beginner-01","beginner-02"].includes(id)&&value.point&&!(pending&&id===challengeId)?1:0),0);
  const checking=busy==="Checking your prompt and judgment.";
  const titles=["Your mission","This prompt needs a boost","Make one useful edit","See what AI made","Does it do the job?",pending?"Your result needs saving":s.stage==="complete"?(review?"Practice complete":"A Prompt Gully win!"):s.stage==="example"?"Completed with help":"One more useful change"];
  const answerViewer=<section className="answer-section" id="answer-view" aria-label="Answer comparison"><div className="answer-tabs" role="tablist" aria-label="Compare answers"><button role="tab" id="tab-new" aria-controls="phone-answer" aria-selected={tab==="new"} onClick={()=>compare("new")}>{s.previousAnswer?"Revised answer":"Your answer"}</button><button role="tab" id="tab-old" aria-controls="phone-answer" aria-selected={tab==="old"} onClick={()=>compare("old")}>{s.previousAnswer?"Previous answer":"Original answer"}</button></div><article className="phone-answer" id="phone-answer" role="tabpanel" aria-labelledby={tab==="new"?"tab-new":"tab-old"} ref={answerBody}><Answer text={tab==="new"?s.answer?.text:old}/></article></section>;
  function onward(){if(review)return <button className="primary" onClick={startFinal} disabled={locked}>Start fresh final</button>;return challengeId==="beginner-01"?<button className="primary" onClick={()=>openPractice("beginner-02")} disabled={locked}>Next challenge</button>:<button className="primary" onClick={startFinal} disabled={locked}>Start final challenge</button>;}
  return <div className="practice-world"><header className="game-header"><a className="wordmark" href="/" aria-label="Prompt Gully"><span>Prompt</span><span className="gully-tag">Gully</span><span className="spark-mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/></svg></span></a><span className="game-points points">{pointCount} / 6 <span>skill points</span></span></header><main className="practice-game"><div className="lesson-top"><div className="step-meta"><span>{review?"Return to practice":`Beginner · Practice ${challengeId==="beginner-01"?1:2}`}</span><details className="level-menu"><summary>My progress</summary><Progress state={s} pending={pending} challengeId={challengeId} records={records} onOpen={openPractice} disabled={locked}/></details></div><div className="lesson-progress" role="progressbar" aria-label="Practice steps" aria-valuemin={1} aria-valuemax={6} aria-valuenow={current} aria-valuetext={`Step ${current} of 6: ${names[current-1]}`}><span style={{width:`${current/6*100}%`}}/></div><div className="step-meta"><span>Step {current} of 6 · {names[current-1]}</span><span>{s.attempts} of 3 attempts used</span></div></div><div className="lesson-workspace"><div className="step-heading"><span className="step-token" aria-hidden="true">{current===6&&s.point&&!pending?<svg viewBox="0 0 24 24"><path d="m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z"/></svg>:current}</span><h1 ref={heading} tabIndex={-1}>{titles[current-1]}</h1></div>{current>2&&<p className="mission-title">{task.title}</p>}
    {preview&&<p className="evidence" role="note">This is a prepared example, not a new AI answer.</p>}
    {saveError&&!pending&&<p className="error" role="alert">This edit could not be saved on this device. Keep this page open and copy your work before leaving.</p>}
    {pending&&<section className="error" role="alert"><h3>Result checked - Save pending</h3><p>Your work is still on this page. Retry saving the same result; your answer will not be assessed again.</p><button className="primary" onClick={retrySaving}>Retry saving</button></section>}
    {error&&<p className="error" role="alert">{error}</p>}
    {busy&&!checking&&<p className="busy" role="status">{busy} Your work remains visible.</p>}
    {current===1&&<section className="task-screen"><h2>{task.title}</h2><p>{task.brief}</p><Requirements task={task} open/><button className="primary" onClick={()=>go(2)} disabled={!!busy||!!pending}>See the starting prompt</button></section>}
    {current===2&&<section className="mission-start"><h2>The starting prompt</h2><blockquote>{task.startingPrompt}</blockquote><p className="evidence">Weak answer (prepared example)</p><div className="weak-answer"><Answer text={task.original}/></div><p className="what-to-notice">{notice}</p><p className="learning-cue">{learningCue}</p><button className="primary" onClick={()=>go(3)} disabled={!!busy||!!pending}>Improve this prompt</button></section>}
    {current===3&&<section className="editor">{s.correcting&&<section className="feedback"><h2>Your feedback</h2><p><strong>Gap:</strong> {feedback.gap}</p><p>{feedback.why}</p></section>}<Requirements task={task}/><label htmlFor="prompt">{s.correcting?"Edit your prompt":"Edit this prompt"}</label><p id="prompt-help">Add the missing detail. You do not need to start over.</p><textarea id="prompt" rows={6} maxLength={6000} value={s.prompt} onChange={e=>edit("prompt",e.target.value)} aria-describedby="prompt-help" disabled={!!busy||!!pending||errorAction==="assess"}/>{s.correcting&&<><label htmlFor="explanation">What did you change, and why?</label><textarea id="explanation" rows={3} value={s.explanation} maxLength={6000} onChange={e=>edit("explanation",e.target.value)} disabled={!!busy||!!pending}/><details><summary>Review the previous answer</summary><Answer text={s.answer?.text}/></details></>}<button className="primary" onClick={generate} disabled={!!busy||!!pending||errorAction==="assess"||allowanceReached}>{s.correcting?"Generate revised answer":"Generate answer"}</button></section>}
    {current===4&&<><p>Check the ideas and the details. A confident answer can still miss something.</p><Requirements task={task}/>{answerViewer}<details className="submitted"><summary>Submitted prompt</summary><p>{s.prompt}</p></details><button className="primary" onClick={()=>go(5)} disabled={!!busy||!!pending}>Write my judgment</button><button className="back-action" onClick={editPrompt} disabled={locked}>Edit my prompt</button></>}
    {current===5&&<section className="judgment"><Requirements task={task}/><details className="read-answer" open={allowanceReached||undefined}><summary>Read the answer</summary>{answerViewer}</details>{s.correcting&&!s.previousAnswer&&<section className="feedback"><h2>Your feedback</h2><p>{feedback.gap}</p><p>{feedback.why}</p>{s.previousJudgment&&<p className="evidence"><strong>Your previous judgment:</strong> {s.previousJudgment}</p>}</section>}<label htmlFor="judgment">{s.correcting&&s.previousAnswer?"Does this revised answer meet the task? Explain why.":"Does your answer meet the task? Explain why."}</label><p>Say what it gets right, what it misses, and what you checked.</p><textarea id="judgment" rows={5} value={s.judgment} maxLength={6000} onChange={e=>edit("judgment",e.target.value)} disabled={!!busy||!!pending||errorAction==="assess"}/>{s.correcting&&!s.previousAnswer&&<><label htmlFor="explanation">What did you change in your judgment, and why?</label><textarea id="explanation" rows={3} value={s.explanation} maxLength={6000} onChange={e=>edit("explanation",e.target.value)} disabled={!!busy||!!pending||errorAction==="assess"}/></>}{s.correcting&&s.previousAnswer&&<p className="evidence"><strong>Your explanation:</strong> {s.explanation}</p>}<div className="assessment-action"><button className="primary" onClick={assess} disabled={!!busy||!!pending||allowanceReached}>{checking?"Checking your judgment":errorAction==="assess"?"Retry assessment":s.correcting?(s.previousAnswer?"Check my correction":"Check my corrected judgment"):"Check my judgment"}</button>{checking&&<span className="assessment-status" role="status">Your work stays here.</span>}</div></section>}
    {current===6&&<section className="result">{s.stage==="complete"&&<>{!pending&&!review&&<h2 className="earned-label">You earned 1 skill point!</h2>}<div className={`point-celebration${celebrate?" celebrating":""}`} aria-hidden="true"><span className="point-medallion">{pending?"…":review?"✓":"+1"}</span>{celebrate&&Array.from({length:8},(_,i)=><span className="confetti" key={i} style={{"--angle":`${i*45}deg`}}>{i%2?"●":"✦"}</span>)}</div><p className="mission-outcome success-summary">{pending?"Your result is checked; save it to confirm the point.":review?"You completed this supported practice. No additional skill point.":successSummary}</p>{!pending&&errorAction!=="recheck"&&!(review&&variantsExhausted)&&onward()}</>}{s.stage==="feedback"&&<><section className="feedback"><p><strong>Gap:</strong> {feedback.gap}</p><p><strong>Why it matters:</strong> {feedback.why}</p><p className="evidence">{feedback.evidence}</p></section>{!pending&&errorAction!=="recheck"&&<button className="primary" onClick={tryAgain} disabled={!!busy}>Try again</button>}</>}{s.stage==="example"&&<><p>You used your two retries. Compare your work with this example.</p><h2>One useful prompt</h2><p>{task.examplePrompt}</p><h2>Example answer</h2><Answer text={task.exampleAnswer}/><p>{task.exampleWhy}</p><p className="completion-note">No independent skill point earned. This does not prevent taking a fresh final later.</p>{!pending&&errorAction!=="recheck"&&!(review&&variantsExhausted)&&onward()}</>}{s.feedback&&<details className="assessment-details" open={allowanceReached||undefined}><summary>Assessment details</summary><p>{feedback.why}</p><p className="evidence">{feedback.evidence}</p><h3>Submitted prompt</h3><p>{s.prompt}</p><h3>Your answer</h3><Answer text={s.answer?.text}/><h3>Your judgment</h3><p>{s.judgment}</p>{s.explanation&&<><h3>What you changed and why</h3><p>{s.explanation}</p></>}</details>}{s.feedback&&!s.feedback.rechecked&&!pending&&<button className={errorAction==="recheck"?"primary":"assessment-challenge"} onClick={challenge} disabled={!!busy||allowanceReached}>{errorAction==="recheck"?"Retry assessment":"Challenge this assessment"}</button>}{review&&variantsExhausted&&<p>Keep practising. Another fresh final challenge is needed to unlock the next level.</p>}</section>}
    {!busy&&!pending&&current>1&&current<6&&current!==4&&<button className="back-action" onClick={()=>go(current===5?4:current-1)} disabled={s.correcting&&current===3||current===3&&!!s.answer}>Back{current===5?" to answer":""}</button>}
    <footer className="save-note"><p>{saveError?"Device saving failed. Keep this page open.":"Saved on this device only. Account backup is not available yet."}</p></footer>
  </div></main></div>;
}
